In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df= pd.read_csv("Movies_IMDB.csv")
df

,Unnamed: 0,movie_name,year,rating,certificate,gross_income,votes,runtime,genre,description,directors,stars
0,0,The Shawshank Redemption,(1994),9.3,A,$28.34M,"2,836,582",142 min,Drama,"Over the course of several years, two convicts...",Frank Darabont,"Stars:Tim Robbins, Morgan Freeman, Bob Gu..."
1,1,The Dark Knight,(2008),9.0,UA,$534.86M,"2,818,034",152 min,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Stars:Christian Bale, Heath Ledger, Aaron..."
2,2,Inception,(2010),8.8,UA,$292.58M,"2,501,258",148 min,"Action, Adventure, Sci-Fi",A thief who steals corporate secrets through t...,Christopher Nolan,"Stars:Leonardo DiCaprio, Joseph Gordon-Le..."
3,3,Fight Club,(1999),8.8,A,$37.03M,"2,272,292",139 min,Drama,An insomniac office worker and a devil-may-car...,David Fincher,"Stars:Brad Pitt, Edward Norton, Meat Loaf..."
4,4,Pulp Fiction,(1994),8.9,A,$107.93M,"2,176,156",154 min,"Crime, Drama","The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"Stars:John Travolta, Uma Thurman, Samuel ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,The Sixth Man,(1997),5.6,PG-13,$14.71M,"6,237",107 min,"Comedy, Drama, Fantasy",A college athlete returns from the dead to hel...,Randall Miller,"Stars:Marlon Wayans, Kadeem Hardison, Dav..."
9996,9996,Vincere,(2009),6.8,Not Rated,$0.62M,"5,849",128 min,"Biography, Drama, Romance","The story of Mussolini's secret lover, Ida Dal...",Marco Bellocchio,"Stars:Giovanna Mezzogiorno, Filippo Timi,..."
9997,9997,Die Feuerzangenbowle,(1944),7.7,Not Rated,0,0,97 min,"Comedy, Family","A successful writer, home-schooled in his yout...",Helmut Weiss,"Stars:Heinz Rühmann, Karin Himboldt, Hild..."
9998,9998,Gloria,(1999),5.1,A,$4.16M,"6,148",108 min,"Crime, Drama, Thriller",After serving three years in prison covering f...,Sidney Lumet,"Stars:Sharon Stone, Jean-Luke Figueroa, J..."
9999,9999,L'Apollonide (Souvenirs de la maison close),(2011),6.7,Not Rated,$0.02M,"7,599",122 min,Drama,At an elegant Parisian bordello at the dawn of...,Bertrand Bonello,"Stars:Noémie Lvovsky, Hafsia Herzi, Célin..."

In [7]:
df= df.drop_duplicates()
df

,Unnamed: 0,movie_name,year,rating,certificate,gross_income,votes,runtime,genre,description,directors,stars
0,0,The Shawshank Redemption,(1994),9.3,A,$28.34M,"2,836,582",142 min,Drama,"Over the course of several years, two convicts...",Frank Darabont,"Stars:Tim Robbins, Morgan Freeman, Bob Gu..."
1,1,The Dark Knight,(2008),9.0,UA,$534.86M,"2,818,034",152 min,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Stars:Christian Bale, Heath Ledger, Aaron..."
2,2,Inception,(2010),8.8,UA,$292.58M,"2,501,258",148 min,"Action, Adventure, Sci-Fi",A thief who steals corporate secrets through t...,Christopher Nolan,"Stars:Leonardo DiCaprio, Joseph Gordon-Le..."
3,3,Fight Club,(1999),8.8,A,$37.03M,"2,272,292",139 min,Drama,An insomniac office worker and a devil-may-car...,David Fincher,"Stars:Brad Pitt, Edward Norton, Meat Loaf..."
4,4,Pulp Fiction,(1994),8.9,A,$107.93M,"2,176,156",154 min,"Crime, Drama","The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"Stars:John Travolta, Uma Thurman, Samuel ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,The Sixth Man,(1997),5.6,PG-13,$14.71M,"6,237",107 min,"Comedy, Drama, Fantasy",A college athlete returns from the dead to hel...,Randall Miller,"Stars:Marlon Wayans, Kadeem Hardison, Dav..."
9996,9996,Vincere,(2009),6.8,Not Rated,$0.62M,"5,849",128 min,"Biography, Drama, Romance","The story of Mussolini's secret lover, Ida Dal...",Marco Bellocchio,"Stars:Giovanna Mezzogiorno, Filippo Timi,..."
9997,9997,Die Feuerzangenbowle,(1944),7.7,Not Rated,0,0,97 min,"Comedy, Family","A successful writer, home-schooled in his yout...",Helmut Weiss,"Stars:Heinz Rühmann, Karin Himboldt, Hild..."
9998,9998,Gloria,(1999),5.1,A,$4.16M,"6,148",108 min,"Crime, Drama, Thriller",After serving three years in prison covering f...,Sidney Lumet,"Stars:Sharon Stone, Jean-Luke Figueroa, J..."
9999,9999,L'Apollonide (Souvenirs de la maison close),(2011),6.7,Not Rated,$0.02M,"7,599",122 min,Drama,At an elegant Parisian bordello at the dawn of...,Bertrand Bonello,"Stars:Noémie Lvovsky, Hafsia Herzi, Célin..."

In [9]:
df=df.rename(columns={"gross_income":"gross_income(Million)"})
df=df.rename(columns={"runtime":"runtime(min)"})

In [11]:
df["gross_income(Million)"]=df["gross_income(Million)"].apply(lambda x : x.replace("M"," ").replace("$"," "))
df["votes"]=df["votes"].apply(lambda x : x.replace(","," ").replace(" ",""))
df["runtime(min)"]= df["runtime(min)"].str.replace("min"," ")
df["stars"]= df["stars"].str.replace("Stars:"," ")
df['year'] =  df['year'].apply(lambda x: x.replace('(','').replace(')','').replace('V','').replace('ideo','').replace('T Moie','').replace('X','').replace('T Movie','').replace('I',''))

In [13]:
df=df.reset_index(drop=True)
df

,Unnamed: 0,movie_name,year,rating,certificate,gross_income(Million),votes,runtime(min),genre,description,directors,stars
0,0,The Shawshank Redemption,1994,9.3,A,28.34,2836582,142,Drama,"Over the course of several years, two convicts...",Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton,..."
1,1,The Dark Knight,2008,9.0,UA,534.86,2818034,152,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckh..."
2,2,Inception,2010,8.8,UA,292.58,2501258,148,"Action, Adventure, Sci-Fi",A thief who steals corporate secrets through t...,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt,..."
3,3,Fight Club,1999,8.8,A,37.03,2272292,139,Drama,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zac..."
4,4,Pulp Fiction,1994,8.9,A,107.93,2176156,154,"Crime, Drama","The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Ja..."
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,The Sixth Man,1997,5.6,PG-13,14.71,6237,107,"Comedy, Drama, Fantasy",A college athlete returns from the dead to hel...,Randall Miller,"Marlon Wayans, Kadeem Hardison, David Pa..."
9996,9996,Vincere,2009,6.8,Not Rated,0.62,5849,128,"Biography, Drama, Romance","The story of Mussolini's secret lover, Ida Dal...",Marco Bellocchio,"Giovanna Mezzogiorno, Filippo Timi, Faus..."
9997,9997,Die Feuerzangenbowle,1944,7.7,Not Rated,0,0,97,"Comedy, Family","A successful writer, home-schooled in his yout...",Helmut Weiss,"Heinz Rühmann, Karin Himboldt, Hilde Ses..."
9998,9998,Gloria,1999,5.1,A,4.16,6148,108,"Crime, Drama, Thriller",After serving three years in prison covering f...,Sidney Lumet,"Sharon Stone, Jean-Luke Figueroa, Jeremy..."
9999,9999,L'Apollonide (Souvenirs de la maison close),2011,6.7,Not Rated,0.02,7599,122,Drama,At an elegant Parisian bordello at the dawn of...,Bertrand Bonello,"Noémie Lvovsky, Hafsia Herzi, Céline Sal..."

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             10000 non-null  int64
 1   movie_name             10000 non-null  object
 2   year                   10000 non-null  object
 3   rating                 10000 non-null  float64
 4   certificate            10000 non-null  object
 5   gross_income(Million)  10000 non-null  object
 6   votes                  10000 non-null  object
 7   runtime(min)           10000 non-null  object
 8   genre                  10000 non-null  object
 9   description            10000 non-null  object
 10  directors              10000 non-null  object
 11  stars                  9998 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 937.6+ KB

In [17]:
df['runtime(min)']= df['runtime(min)'].astype(int)
df["votes"]= df["votes"].astype(int)
df['gross_income(Million)']=df["gross_income(Million)"].astype(float)
df['year']=df["year"].astype(int)

In [19]:
df.isnull().sum()

Unnamed: 0               0
movie_name               0
year                     0
rating                   0
certificate              0
gross_income(Million)    0
votes                    0
runtime(min)             0
genre                    0
description              0
directors                0
stars                    2
dtype: int64

In [21]:
df['stars']=df['stars'].fillna(method='pad')
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_13808\759337559.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['stars']=df['stars'].fillna(method='pad')

,Unnamed: 0,movie_name,year,rating,certificate,gross_income(Million),votes,runtime(min),genre,description,directors,stars
0,0,The Shawshank Redemption,1994,9.3,A,28.34,2836582,142,Drama,"Over the course of several years, two convicts...",Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton,..."
1,1,The Dark Knight,2008,9.0,UA,534.86,2818034,152,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckh..."
2,2,Inception,2010,8.8,UA,292.58,2501258,148,"Action, Adventure, Sci-Fi",A thief who steals corporate secrets through t...,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt,..."
3,3,Fight Club,1999,8.8,A,37.03,2272292,139,Drama,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zac..."
4,4,Pulp Fiction,1994,8.9,A,107.93,2176156,154,"Crime, Drama","The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Ja..."
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,The Sixth Man,1997,5.6,PG-13,14.71,6237,107,"Comedy, Drama, Fantasy",A college athlete returns from the dead to hel...,Randall Miller,"Marlon Wayans, Kadeem Hardison, David Pa..."
9996,9996,Vincere,2009,6.8,Not Rated,0.62,5849,128,"Biography, Drama, Romance","The story of Mussolini's secret lover, Ida Dal...",Marco Bellocchio,"Giovanna Mezzogiorno, Filippo Timi, Faus..."
9997,9997,Die Feuerzangenbowle,1944,7.7,Not Rated,0.00,0,97,"Comedy, Family","A successful writer, home-schooled in his yout...",Helmut Weiss,"Heinz Rühmann, Karin Himboldt, Hilde Ses..."
9998,9998,Gloria,1999,5.1,A,4.16,6148,108,"Crime, Drama, Thriller",After serving three years in prison covering f...,Sidney Lumet,"Sharon Stone, Jean-Luke Figueroa, Jeremy..."
9999,9999,L'Apollonide (Souvenirs de la maison close),2011,6.7,Not Rated,0.02,7599,122,Drama,At an elegant Parisian bordello at the dawn of...,Bertrand Bonello,"Noémie Lvovsky, Hafsia Herzi, Céline Sal..."

In [23]:
df.isnull().sum()

Unnamed: 0               0
movie_name               0
year                     0
rating                   0
certificate              0
gross_income(Million)    0
votes                    0
runtime(min)             0
genre                    0
description              0
directors                0
stars                    0
dtype: int64

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle
import os

# Function to combine features
def combine_features(row):
    return f"{row['description']} {row['genre']} {row['directors']} {row['stars']}"

# Load your dataset
def load_data():
    data = pd.read_csv('Movies_IMDB.csv')  # Replace with your file path
    data['combined_features'] = data.apply(combine_features, axis=1)
    return data

# Save data and model to pickle
def save_to_pickle(df):
    df.reset_index(drop=False, inplace=True)  # Ensure 'index' is a column
    pickle.dump(df, open('movie_data.pkl', 'wb'))

    tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 1), min_df=0.0, stop_words='english')
    tfidf_matrix = tf.fit_transform(df['combined_features']).toarray()
    pickle.dump(tf, open('tfidf_vectorizer.pkl', 'wb'))
    pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

# Main execution
if __name__ == "__main__":
    df = load_data()
    save_to_pickle(df)
    print("Pickle files created successfully!")

Pickle files created successfully!

In [31]:
import gzip
import pickle

def compress_pickle(input_file, output_file):
    with open(input_file, 'rb') as f_in:
        with gzip.open(output_file, 'wb') as f_out:
            f_out.writelines(f_in)

# Compress your TF-IDF files
compress_pickle('tfidf_vectorizer.pkl', 'tfidf_vectorizer.pkl.gz')
compress_pickle('tfidf_matrix.pkl', 'tfidf_matrix.pkl.gz')